mod compilation_unit;
pub use compilation_unit::*;
mod declarations;
pub use declarations::*;
mod modifiers;
pub use modifiers::*;
mod statements;
pub use statements::*;
mod expressions;
pub use expressions::*;
mod types;
pub use types::*;
mod identifiers;
pub use identifiers::*;
pub mod switch;
pub use switch::*;
mod printer;
pub mod patterns;
pub use patterns::*;

pub type Program = CompilationUnit;
pub type Multiple<T> = Vec<T>;
